# Make sure your Operating system uses netplan 
# debian based and Centos based netplan configuration folder /etc/netplan/
# Have tested ubuntu 19.* up to 22.04
# centos 9 stream, OL8 x86-64 kernel and OL9 UEK kernel
#Netplan configuration 
#Generally use this to learn lxd with macvlan
#In lxd this configuration will let the container see the lxd bridge and the wan network

network: # This is the network
  version: 2
  ethernets: # Nic devices they can be virtualized or hardware
    eth0: # network device - make sure you have the correct network device
      dhcp4: true # This allows for dynamic IP
    eth1: # Network device - make sure you have the correct network device
      dhcp4: false # To set static IPV4
      addresses: [192.5.4.150/24] # Here you choose the static ip
      gateway4: 192.5.3.4.1 # You have to change this to your default gateway
      nameservers:
        addresses: [1.1.1.3,1.0.0.3] # CLOUDFLARE DNS, you can choose your own
    #eth2: #you can add as many devices as allowed in your network device configuration
      #dhcp4: true